### ISSUE TITLE
Checklist for Kinetic Beta 

### ISSUE THREAD

**Issue by beeman** [kin-labs/kinetic#67]
In this issue we track the things that are needed for the Kinetic Beta release:

## Prio 1 (Beta)
- [x] implement e2e tests #35
- [x] implement health endpoint #34 
- [x] #120
- [x] #110
- [x] #78
- [x] Admin API: #71 
  - [x] Implement Authenticated endpoints #81
  - [x] Management of Apps #85 
  - [x] Management of Users #86 
  - [x] Management of App User #88 
  - [x] Management of App Wallets #90 
  - [x] Implement Admin UI to manage the above 
- [x] #104
- [x] #138
- [x] #106
- [x] #109
- [x] #107
- [x] #105
- [x] #108
- [x] #139
- [x] #125 

## Prio 2 (Pre-release)
- [x] #114
- [x] #168
- [x] #173 
- [x] #166
- [x] #181 
- [x] #121
- [x] #217
- [x] #218
- [ ] Add Rate limiting to the API
- [ ] Logging #405 
- [ ] Add 'sender create' functionality #316 
- [ ] Make SDKs send their user agent #377 
- [x] #356
- [x] #357

## Prio 3 (Release)
- [ ] Whatever needs to be done before releasing the final Kinetic 1.0.0
